getting somwehere
Limmen/csle pull request #318
Opened 2023-10-06 15:10 UTC by nforsg

Jobbar med att implementera CMA-ES

2023-10-07 09:17 UTC, nforsg commented
Liten uppdatering: Har kommit en bit på vägen, men behöver göra en liten manöver för att göra biblioteket cma riktigt nöjd. Den finns en modul med en funktion där som heter optimize(f), som tar funktionen f (J i vårt fall) och optmierar den utifrån någon initial vektor, men den vill att J ska vara en ren funktion av theta. Jobbar vidare

2023-10-07 10:08 UTC, nforsg commented
Okej, så nu har jag åstadkommit ett resultat, men det finns några problem.

Som jag nämnde tidigare måste jag göra vissa undantag för att satisifiera biblioteket cma. Jag avparametriserade eval_theta och utvärderiade det som tidigare var parametrar i funktionen istället. 
Därefter gjorde jag en ren funktion J som kallade på eval_theta. Allt detta hade då bara theta som parameter, just för att det är så funktionen optimize ( i cma) fungerar. Jag definierade avg_metrics längre ned i funktionen cma_es, i syfte att inte vara destruktiv mot den log som dyker upp under simuleringen. Ytterigare ett problem som upstod är att biblioteket cma overridear våran implementerade logg med sin egna logg vid körning. 

Finns nog en del saker som går att lös, men behöver en checkpoint med feedback innan jag går vidare. Men nu verkar det funka iallafall.

2023-10-07 17:03 UTC, Limmen requested changes
Det ser bra ut. Lite små grejer att fixa men annars ser allt korrekt ut. En del extra filer som kommit med i PR som kan tas bort.

2023-10-07 17:03 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/cma_es_agent.py
> +        parameter_bounds = self.experiment_config.hparams[agents_constants.CMA_ES_OPTIMIZATION.PARAMETER_BOUNDS].value
Används dessa bounds på något sätt eller är de bara kopierade från en annan agent? Om de inte används så kan de tas bort

2023-10-07 17:03 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/cma_es_agent.py
> +                    f"[BAYES-OPT] i: {i}, J:{J}, "
CMA-ES istället för BAYES-OPT

2023-10-07 17:03 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/cma_es_agent.py
> +    def get_theta_vector_from_param_dict(param_dict: Dict[str, float]) -> List[float]:
Används denna metoden? Ta bort annars

2023-10-07 17:05 UTC, Limmen commented
> Det ser bra ut. Lite små grejer att fixa men annars ser allt korrekt ut. En del extra filer som kommit med i PR som kan tas bort.

Efter att du fixat detta så kommer jag testköra din branch. Jag tror inte det där med logger kommer vara ett stort problem, antagligen kan man konfigurera log-nivån för CMA-ES biblioteket. Angående lösningen med def J(..) så är det en bra lösning!

2023-10-08 14:08 UTC, nforsg commented
Fixat. Vet inte riktigt varför det (auto-)genererades file rdär, dom verkar inte dyka upp vid körning nu iaf.

2023-10-08 14:11 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/cma_es_agent.py
> +        parameter_bounds = self.experiment_config.hparams[agents_constants.CMA_ES_OPTIMIZATION.PARAMETER_BOUNDS].value
parameter_bounds verkar inte användas, så tar bort det.

2023-10-08 14:13 UTC, nforsg commented on examples/training/cma_es/stopping_pomdp_defender/outcmaes/axlen.dat
> +% # columns="iteration, evaluation, sigma, max axis length,  min axis length, all principal axes lengths  (sorted square roots of eigenvalues of C)", seed=781784, Sat Oct  7 12:02:40 2023
fuxat

2023-10-08 14:13 UTC, nforsg commented on examples/training/cma_es/stopping_pomdp_defender/outcmaes/axlencorr.dat
> +% # columns="iteration, evaluation, min max(neg(.)) min(pos(.)) max correlation, correlation matrix principal axes lengths  (sorted square roots of eigenvalues of correlation matrix)", seed=781784, S
Fixat

2023-10-08 14:13 UTC, nforsg commented on examples/training/cma_es/stopping_pomdp_defender/outcmaes/axlenprec.dat
> +% # columns="iteration, evaluation, min max(neg(.)) min(pos(.)) max correlation, correlation matrix principal axes lengths  (sorted square roots of eigenvalues of correlation matrix)", seed=781784, S
Fixat

2023-10-08 14:13 UTC, nforsg commented on examples/training/cma_es/stopping_pomdp_defender/outcmaes/fit.dat
> +% # columns="iteration, evaluation, sigma, axis ratio, bestever, best, median, worst objective function value, further objective values of best", seed=781784, Sat Oct  7 12:02:40 2023, <python>{}</py
Fixat

2023-10-08 14:13 UTC, nforsg commented on examples/training/cma_es/stopping_pomdp_defender/outcmaes/sigvec.dat
> +% # columns="iteration, evaluation, sigma, beta, void,  sigvec==sigma_vec.scaling factors from diagonal decoding", seed=781784, Sat Oct  7 12:02:40 2023, <python>{}</python>
Fixat

2023-10-08 14:14 UTC, nforsg commented on examples/training/cma_es/stopping_pomdp_defender/outcmaes/stddev.dat
> +% # columns="iteration, evaluation, sigma, void, void,  stds==sigma*sigma_vec.scaling*sqrt(diag(C))", seed=781784, Sat Oct  7 12:02:40 2023, <python>{}</python>
Fixat

2023-10-08 14:14 UTC, nforsg commented on examples/training/cma_es/stopping_pomdp_defender/outcmaes/xmean.dat
> +% # columns="iteration, evaluation, void, void, void, xmean", seed=781784, Sat Oct  7 12:02:40 2023, <python>{}</python> # scaling_of_variables: 1, typical_x: 0
Fixat

2023-10-08 14:14 UTC, nforsg commented on examples/training/cma_es/stopping_pomdp_defender/outcmaes/xrecentbest.dat
> +% # columns="iter, evals, sigma, 0, fitness, xbest" seed=781784, Sat Oct  7 12:02:40 2023, <python>{}</python>
Fixat

2023-10-08 14:14 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/outcmaes/axlen.dat
> +% # columns="iteration, evaluation, sigma, max axis length,  min axis length, all principal axes lengths  (sorted square roots of eigenvalues of C)", seed=640032, Fri Oct  6 18:30:51 2023
Fixat

2023-10-08 14:14 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/outcmaes/axlencorr.dat
> +% # columns="iteration, evaluation, min max(neg(.)) min(pos(.)) max correlation, correlation matrix principal axes lengths  (sorted square roots of eigenvalues of correlation matrix)", seed=640032, F
Fixat

2023-10-08 14:14 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/outcmaes/axlenprec.dat
> +% # columns="iteration, evaluation, min max(neg(.)) min(pos(.)) max correlation, correlation matrix principal axes lengths  (sorted square roots of eigenvalues of correlation matrix)", seed=640032, F
Fixat

2023-10-08 14:14 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/outcmaes/fit.dat
> +% # columns="iteration, evaluation, sigma, axis ratio, bestever, best, median, worst objective function value, further objective values of best", seed=640032, Fri Oct  6 18:30:51 2023, <python>{}</py
Fixat

2023-10-08 14:14 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/outcmaes/sigvec.dat
> +% # columns="iteration, evaluation, sigma, beta, void,  sigvec==sigma_vec.scaling factors from diagonal decoding", seed=640032, Fri Oct  6 18:30:51 2023, <python>{}</python>
Fixat

2023-10-08 14:14 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/outcmaes/stddev.dat
> +% # columns="iteration, evaluation, sigma, void, void,  stds==sigma*sigma_vec.scaling*sqrt(diag(C))", seed=640032, Fri Oct  6 18:30:51 2023, <python>{}</python>
Fixat

2023-10-08 14:14 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/outcmaes/xmean.dat
> +% # columns="iteration, evaluation, void, void, void, xmean", seed=640032, Fri Oct  6 18:30:51 2023, <python>{}</python> # scaling_of_variables: 1, typical_x: 0
Fixat

2023-10-08 14:14 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/outcmaes/xrecentbest.dat
> +% # columns="iter, evals, sigma, 0, fitness, xbest" seed=640032, Fri Oct  6 18:30:51 2023, <python>{}</python>
fixat

2023-10-08 14:15 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/test.py
> +import cma
Fixat

2023-10-08 14:15 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/cma_es_agent.py
> +                    f"[BAYES-OPT] i: {i}, J:{J}, "
Fixat

2023-10-08 14:15 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/cma_es/cma_es_agent.py
> +    def get_theta_vector_from_param_dict(param_dict: Dict[str, float]) -> List[float]:
Tagit bort

2023-10-09 08:01 UTC, Limmen commented
Har fixat loggingen så att CMA inte loggar något utan vi kör bara på vår egna logs.

2023-10-09 08:01 UTC, Limmen commented
Mergar denna så kan du skapa ett Unit test för CMA-ES i en ny branch

2023-10-09 08:02 UTC, merged