some first encounters of torch from tutors
Limmen/csle pull request #333
Opened 2023-12-02 09:29 UTC by nforsg

Jobbar på i denna. Kommer ta bort cleanrl-foldern så småningom.

2023-12-09 14:02 UTC, nforsg commented
försöker få atari att funka problemfritt på GPU, några varningsmeddelanden samt en del trösklar till att initiera breakout-spelet som environment i gym-modulen

2023-12-13 10:39 UTC, nforsg commented
Tror jag börjar komma på banan med intergreringen av cleanrl till vårt bibliotek. Dom kör olika (mer eller mindre många defaults) argparser som parametrar, men om jag fattat rätt ska vår parametrisering gå via hur vi initierar objekt som t.ex SimulationEnvConfig etc. Tröskeln nu efter lunch blir att ändra på sparningen, som gör manuellt i varje steg (tror jag), och inte via en superklass (när vi andvänder stable baselines 3 i vanliga ppo verkar man köra ett väldigt väldesignat inheritance från BaseCallback).

Förhoppningsvis får jag till en körning efter lunch, men en del hinder kvarstår. Har även börjat med att få till en integrering från vanliga ppo.py som finns i cleanrl-biblioteket och inte ppo_atari.py, pga det uppstod så många olika konstiga errors vid körning.

2023-12-13 13:57 UTC, nforsg commented
Har lyckats eliminera alla errors, har dock hårkodat ala parametrar atm och ska förstå mig på alla mer innan jag integrerar till fullo, tror jag använder deras Args-klass då.
Den kör inte än, mn kommer titta vidare på det i vecka och se till så att den gör det.

2023-12-15 10:32 UTC, Limmen commented
Låter bra. Ja precis, vi ska inte ha någon argparse. Du kan ta inspiration från stable-baselines men notera att för olika bibliotek behöver man lite olika sätt att lösa integreringen på, så du kan försöka designa det bästa du kan som passar bäst för cleanRL. Det vi behöver (utöver att kunna träna agenten) är att kunna mäta prestanda vid olika tidpunkter under träningen.

2023-12-19 16:48 UTC, nforsg commented
Kommer jobba imorgon och torsdag denna vecka.

2023-12-20 13:04 UTC, nforsg commented
Okej, då har jag fått till en exekverande kod som använder sig av implementationen ppo.py som finns i CleanRL:s bibliotek. Alla errors är nu "undantvättade" och jag kan lägga mer fokus på bättre parametrisering. Just nu är det lite hårdkodat, men parameteriseringen är av samma karaktär som den i ppo_agent.py. Ska köra lintern, mypy src och göra testfil också.

2023-12-20 13:23 UTC, Limmen commented
> Okej, då har jag fått till en exekverande kod som använder sig av implementationen ppo.py som finns i CleanRL:s bibliotek. Alla errors är nu "undantvättade" och jag kan lägga mer fokus på bättre parametrisering. Just nu är det lite hårdkodat, men parameteriseringen är av samma karaktär som den i ppo_agent.py. Ska köra lintern, mypy src och göra testfil också.

Nice, jag ger dig en första högnivå review strax. Sedan kan du säga till när du fixat linter m.m och hårdkodningen så gör jag en till review och testkör koden.

2023-12-20 13:24 UTC, Limmen requested changes
Första högnivå review med lite förslag på refaktorering.

2023-12-20 13:42 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +            self.simulation_env_config.name = "JohnDoe"
Nope den var helt betydelselös

2023-12-20 15:32 UTC, nforsg commented on examples/pilot_algorithms/argparse_pilot.py
> +from argparse import ArgumentParser
fixat

2023-12-20 15:33 UTC, nforsg commented on examples/pilot_algorithms/pilot1.py
> +import torch
fixat

2023-12-20 15:33 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +        def thunk():
fixat ( tror jag)

2023-12-20 15:33 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +def layer_init(layer, std=np.sqrt(2), bias_const=0.0):
jag tror jag har fått till denna nu.

2023-12-20 15:33 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +class Agent(nn.Module):
jag tror jag har fått till denna nu.

2023-12-20 15:34 UTC, nforsg commented
har följt denna tutor för att få till PPONetwork-klassen: 
https://www.youtube.com/watch?v=jhPsC4fe2bQ

Hade ImportModuleError. Löste problemet med denna tutor: 
https://www.youtube.com/watch?v=Mgp6-ZMEcE0

2023-12-20 15:47 UTC, nforsg commented
fortsätter imorgon.

2023-12-21 09:34 UTC, Limmen commented
> har följt denna tutor för att få till PPONetwork-klassen: https://www.youtube.com/watch?v=jhPsC4fe2bQ
> 
> Hade ImportModuleError. Löste problemet med denna tutor: https://www.youtube.com/watch?v=Mgp6-ZMEcE0 (Obs: tom **init**.py-fil gjorde ingen skillnad/löste inte problemet)

PPONetwork ser bra ut. Setup.py filen behövs inte, det kan lösas utan den. Men du kan ha kvar den så länge i fall det gör att du kan importera korrekt så kan jag fixa det senare när koden är klar.

2023-12-21 11:05 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +        clip_coef = 0.2
Ska jag göra en egen sub-klass under csle_agents.constants.constants som heter PPO_CLEAN? Så jag kan ha ett eget konstant-rum för just PPO-clean (det är typ num_minibatches och nån mer inte finns med i PPO)

2023-12-21 11:58 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +        clip_coef = 0.2
Nu är dock förhållande mellan de olika värdena dem samma, men för total-timesteps = 80000

2023-12-21 12:06 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +            for iteration in range(1, num_iterations + 1):
Jag ska prova göra attribut av alla hyper-params som jag hämtar från dicten i denna agent-klass, så refaktorieringen inte består av funktioner som måste ta en massa parametrar utan kan använda klassens attribut.

2023-12-21 13:01 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +            for iteration in range(1, num_iterations + 1):
Så nu är en del av koden som finns i en av looparna refaktorerad till funktionerna next_setter och bootstrap. Har dessutom gjort om många hyper-params till attribut, tycker det blev bättre (när dom ändå tilldelas samma sak i varje iteration). Om det inte ska refaktoreras mer är detta isf fixat.

2023-12-21 13:02 UTC, nforsg commented on simulation-system/libs/csle-agents/src/csle_agents/agents/ppo_clean/ppo_clean_agent.py
> +        clip_coef = 0.2
fixat.

2023-12-21 13:31 UTC, Limmen commented
Bra jobbat, ska testköra det när jag har tid

2023-12-21 13:47 UTC, nforsg commented
> Bra jobbat, ska testköra det när jag har tid

Jag påbörjar en test-suite samt försöker reda ut errors i mypy sålänge.

2023-12-25 15:57 UTC, merged