import errors
Limmen/csle pull request #353
Opened 2024-03-14 11:04 UTC by nforsg

Har provat klona ner scikit-optimization och köra lokalt, men har haft problem med ett import-error på en fil som heter default än sålänge, jobbarmed att fixa det.

2024-03-14 13:12 UTC, nforsg commented
jag förstår inte riktigt varför jag får modulenotfounderrors när jag kör msc.py i scikits, det ska egentligen inte hända. Jag initierar setup-filen i yttre foldret med "pip install -e .", det löser en del errors, men criterion ska ju finnas som modul och funka i foldern "optimization". Jag jobbar på det, i värsta fall får jag implementera denna själv.

2024-03-15 08:37 UTC, Limmen commented
Behöver du göra ändringar i scikit-biblioteket? Annars finns det ingen anledning att klona det då kan du göra pip install istället

2024-03-15 08:37 UTC, Limmen commented
Radera det klonade biblioteket och kör `pip install -U scikit-learn`

2024-03-15 08:50 UTC, nforsg commented
> Behöver du göra ändringar i scikit-biblioteket? Annars finns det ingen anledning att klona det då kan du göra pip install istället
Jag provade bara klona ner det och köra deras tester för att förstå mig på det från början, men då fick jag en hel del errors pga att det är implementerat i python 2.7 och framförallt gammal syntax för numpy och imports. Ska prova nu när jag uinstallerat

2024-03-15 09:13 UTC, nforsg commented
Alltså det kan vara så att jag missförstått hur man använder det här, men biblioteket sciki-learn https://scikit-learn.org/stable/index.html verkar inte ha något att göra med det biblioteket du skickade via mailen: https://github.com/mbrucher/scikit-optimization eller har jag fel? det är nämligen 12 år gammalt, när man kör pip install -U scikit-learn installerar man ett nyare bibliotek (det som är länkat) det har inte mcs-alghoritmen.

2024-03-15 09:24 UTC, Limmen commented
> Alltså det kan vara så att jag missförstått hur man använder det här, men biblioteket sciki-learn https://scikit-learn.org/stable/index.html verkar inte ha något att göra med det biblioteket du skickade via mailen: https://github.com/mbrucher/scikit-optimization eller har jag fel? det är nämligen 12 år gammalt, när man kör pip install -U scikit-learn installerar man ett nyare bibliotek (det som är länkat) det har inte mcs-alghoritmen.

Du har rätt, sorry. Förvirrande att de har samma namn jag trodde den fanns i officiella scikit. Då kan vi strunta i att förlita oss på 3:e parts biblioteket och implementera MCS från scratch, men vi kan fortfarande ta inspiration från källkoden i det där gamla biblioteket.

2024-03-15 09:32 UTC, nforsg commented
> > Alltså det kan vara så att jag missförstått hur man använder det här, men biblioteket sciki-learn https://scikit-learn.org/stable/index.html verkar inte ha något att göra med det biblioteket du skickade via mailen: https://github.com/mbrucher/scikit-optimization eller har jag fel? det är nämligen 12 år gammalt, när man kör pip install -U scikit-learn installerar man ett nyare bibliotek (det som är länkat) det har inte mcs-alghoritmen.
> 
> Du har rätt, sorry. Förvirrande att de har samma namn jag trodde den fanns i officiella scikit. Då kan vi strunta i att förlita oss på 3:e parts biblioteket och implementera MCS från scratch, men vi kan fortfarande ta inspiration från källkoden i det där gamla biblioteket.

Okej, då fattar jag, ingen fara! Yes då gör jag så.

2024-03-18 15:13 UTC, nforsg commented
Har refaktorerat från detta bibliotek nu: 
https://github.com/vojha-code/Multilevel-Coordinate-Search

Upplever att algoritmen är ganska komplixerad, men nu tror jag att jag ska kunna få till körningar och därefter göra en lite bättre implementation än den befintliga.

2024-03-18 15:48 UTC, Limmen commented
Låter bra, börja med att få den att köra sedan kan vi börja förfina koden. I PR just nu är det 62 nya filer, det borde gå att få ner det till 5 eller så.

2024-04-02 05:56 UTC, nforsg commented
Kanske nämnde det när jag var förbi senast, men jobbar torsdag och fredag denna vecka då tentan är klar imorgon kl 13!

2024-04-04 10:40 UTC, nforsg commented
Har jobbat nu under förmiddagen och det är som jag beskrev senast, eval_theta är det som slukar, mcs_agent fungerar felfritt om man istället kör en enkel 2:a-gradare. Så jag jobbar på att få till en sabb implementation av den.

Har däremot svårt att pusha koden till github, då jag får "Authentication failed", jag kom ihåg från i somras att det var någon liten grej som gjorde att det inte fungerade, men att det var svårt att hitta exakt vad det var, har du stött på samma problem? Jag förnyade min acces token för en vecka sen, men det brukar inte orsaka några problem.

Jag jobbar på under tiden.

2024-04-04 10:47 UTC, Limmen commented
> Har jobbat nu under förmiddagen och det är som jag beskrev senast, eval_theta är det som slukar, mcs_agent fungerar felfritt om man istället kör en enkel 2:a-gradare. Så jag jobbar på att få till en sabb implementation av den.
> 
> Har däremot svårt att pusha koden till github, då jag får "Authentication failed", jag kom ihåg från i somras att det var någon liten grej som gjorde att det inte fungerade, men att det var svårt att hitta exakt vad det var, har du stött på samma problem? Jag förnyade min acces token för en vecka sen, men det brukar inte orsaka några problem.
> 
> Jag jobbar på under tiden.

Det kan vara att din authentication token har gått ut. Du kan testa:
```
git config --global --unset credential.helper
git config credential.helper store
git push origin master
```
Det borde då fråga efter en nytt password och då ska du ange din Github token för ditt konto

2024-04-04 10:57 UTC, nforsg commented
> > Har jobbat nu under förmiddagen och det är som jag beskrev senast, eval_theta är det som slukar, mcs_agent fungerar felfritt om man istället kör en enkel 2:a-gradare. Så jag jobbar på att få till en sabb implementation av den.
> > Har däremot svårt att pusha koden till github, då jag får "Authentication failed", jag kom ihåg från i somras att det var någon liten grej som gjorde att det inte fungerade, men att det var svårt att hitta exakt vad det var, har du stött på samma problem? Jag förnyade min acces token för en vecka sen, men det brukar inte orsaka några problem.
> > Jag jobbar på under tiden.
> 
> Det kan vara att din authentication token har gått ut. Du kan testa:
> 
> ```
> git config --global --unset credential.helper
> git config credential.helper store
> git push origin master
> ```
> 
> Det borde då fråga efter en nytt password och då ska du ange din Github token för ditt konto

Juste, det vara bara det att jag glömde att token var lösenordet, visste att det var nåt sånt där!

2024-04-04 11:01 UTC, nforsg commented
Anyways, algoritmen funkar nu, det handlade bara om att jag satte batch_size = 100, minskade till 10 och då fungerar den korrekt.
Jag fortsätter jobba med att få ner antal filer och gör linter och test-suites och mypy klart och hojtar när implementationen är lkar för review.

2024-04-04 11:31 UTC, Limmen commented
> Anyways, algoritmen funkar nu, det handlade bara om att jag satte batch_size = 100, minskade till 10 och då fungerar den korrekt. Jag fortsätter jobba med att få ner antal filer och gör linter och test-suites och mypy klart och hojtar när implementationen är lkar för review.

Toppen!

2024-04-04 15:38 UTC, nforsg commented
Har fått ner det till 4 filer nu, har gjort ett antal objekt av saker som ser ut att ha liknande funktionalitet. Kommer ägna förmiddagen imorgon åt python linter, och göra så långt jag hinner på resterande implementation img eftermiddag.

2024-04-08 09:37 UTC, Limmen requested changes
Ser bra ut överlag, intressant algoritm. En del saker att förfina/fixa vid nästa tillfälle.

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/README.txt
> +Global optimization by multilevel coordinate search (MCS)
Denna filen kan tas bort.

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +        Initializes the Particle Swarm Agent
MCS

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +        print('The MCS Algorithms Results:')
Försöka att göra om dessa printouts till ett Log-statement som sker varje iteration, likt de andra algoritmerna.

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def init_list(self, theta0, l, L, stopping_actions, n):
Type hints att lägga till

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def MCS(self, u, v, smax, nf, stop, iinit, local, gamma, hess, stopping_actions, eps, n, prt=1):
Type hints

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +                    z[1, par] = m
Den här identeringen är lite väl verbose, försök kombinera det till färre rader

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def splinit(self, i, s, smax, par, x0, n0, u, v, x, y, x1, x2, L, l, xmin, fmi, ipar, level, ichild, f, xbest,
type hints

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def split(self, i, s, smax, par, n0, u, v, x, y, x1, x2, z, xmin,
type hints

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def lsearch(self, x, f, f0, u, v, nf, stop, maxstep, gamma,
type hints

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def basket1(self, x, f, xmin, fmi, xbest, fbest, stop, nbasket, nsweep, nsweepbest, stopping_actions):
type hints

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def csearch(self, x, f, u, v, hess, stopping_actions, eps):
type hints

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def gls(self, xl, xu, x, p, alist, flist, nloc, small, smax, stopping_actions, prt=2):
type hints

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def lsnew(self, nloc, small, sinit, short, x, p, s, alist, flist, amin,
type hints

2024-04-08 09:37 UTC, Limmen commented on simulation-system/libs/csle-agents/src/csle_agents/agents/MCS/mcs_agent.py
> +    def lsquart(self, nloc, small, sinit, short, x, p, alist,
type hints

2024-04-10 09:27 UTC, nforsg commented
Fixar kommentarerna vid nästa jobbtillfälle! Utöver det är det hårdkodning på en del ställen samt fullständigt implementation av våra configurations osv, framförallt när algoritmen är färdigkörd.

2024-04-17 12:32 UTC, Limmen commented
Säg till när PR är redo för review/merge.

2024-04-19 15:09 UTC, nforsg commented
Nu är den hyfsat redo för review. Det är eventuellt några buggar som är lite svåra att detektera, då dom sällan utgör utfall av algoritmen. Jag har i stort sett rensat linter-meddelandena, men det är några väldigt märkliga implementationer som strider mot linter men som ger error vid körning om man gör "rätt", framförallt rad 24 och 29 i gls_utils. Utöver det är en en del variabel-/parameternamn som kanske behöver förfinas. Men loggningen tror jag är rätt bra, och den gör nog det den ska nu.

2024-04-23 11:44 UTC, Limmen commented
> Nu är den hyfsat redo för review. Det är eventuellt några buggar som är lite svåra att detektera, då dom sällan utgör utfall av algoritmen. Jag har i stort sett rensat linter-meddelandena, men det är några väldigt märkliga implementationer som strider mot linter men som ger error vid körning om man gör "rätt", framförallt rad 24 och 29 i gls_utils. Utöver det är en en del variabel-/parameternamn som kanske behöver förfinas. Men loggningen tror jag är rätt bra, och den gör nog det den ska nu.

Bra. Du kan fortsätta förfina koden så mycket du kan (refaktorera, kommentera, type-hinta, etc) vid de kvarstående jobbtillfällena så mergar jag efter det.

2024-04-26 10:51 UTC, nforsg commented
Har gjort klart en del linter och mypy idag samt initerat en test-suite, fortsätter i helgen pga jag behöver göra annat idag.

2024-05-13 17:12 UTC, merged