csle tolerance tests
Limmen/csle pull request #355
Opened 2024-04-24 13:22 UTC by Yuhu-kth

2024-05-03 17:27 UTC, Yuhu-kth commented
In the file "csle/simulation-system/libs/csle-tolerance/tests/test_intrusion_response_cmdp_util.py", line #145-147# :
<img width="1198" alt="Screenshot 2024-05-03 at 19 25 06" src="https://github.com/Limmen/csle/assets/54626501/0f432385-658c-4d69-b12f-a99b27f665ac">

normalizing_constant is overwritten by line 151. So it's a bit weird to me.

2024-05-04 07:29 UTC, Limmen commented
> In the file "csle/simulation-system/libs/csle-tolerance/tests/test_intrusion_response_cmdp_util.py", line #145-#147 : <img alt="Screenshot 2024-05-03 at 19 28 40" width="1188" src="https://private-user-images.githubusercontent.com/54626501/327835469-aea3fe29-6246-49f4-857b-2991e9ff378c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDc5NDQsIm5iZiI6MTcxNDgwNzY0NCwicGF0aCI6Ii81NDYyNjUwMS8zMjc4MzU0NjktYWVhM2ZlMjktNjI0Ni00OWY0LTg1N2ItMjk5MWU5ZmYzNzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA3MjcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZTA3MjczMTU0ODNjODVjNTlhNTQ1YTZjZmMxNmNiMzhhYjA3YTI0MmMzZDFmMmE0ZjFjMzU4N2VkZDFlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a-AiUd-jri5dYrphGd2tsMxnsrclmGT9WhfZa4JlMdw">
> 
> normalizing_constant is overwritten by line 151. So it's a bit weird to me.

Yes you are right, good catch @Yuhu-kth. You can remove the redundant lines, i.e, 145-147

2024-05-04 07:30 UTC, Limmen reviewed
Everything looks good so far. Lets continue with this PR until you completed all tests for csle-tolerance, then I will merge it and we can move on to the next task.

2024-05-15 08:56 UTC, Limmen requested changes
Looks good, small things to fix

2024-05-15 08:56 UTC, Limmen commented on simulation-system/libs/csle-tolerance/src/csle_tolerance/envs/intrusion_recovery_pomdp_env.py
> +            print(i)
Remove print statement

2024-05-15 08:56 UTC, Limmen commented on simulation-system/libs/csle-tolerance/src/csle_tolerance/util/general_util.py
> +        #import logging
Remove comments

2024-05-15 11:51 UTC, merged