test host_manager is running in the container
Limmen/csle pull request #414
Opened 2024-08-12 10:24 UTC by Yuhu-kth

2024-08-12 13:51 UTC, Limmen requested changes
Looks good, one print statement to remove

2024-08-12 13:51 UTC, Limmen commented on emulation-system/tests/test_start_host_manager.py
> +        print(f"Container {container_setup} is running.")
Can remove this print

2024-08-12 14:02 UTC, Yuhu-kth commented on emulation-system/tests/test_start_host_manager.py
> +        print(f"Container {container_setup} is running.")
removed

2024-08-13 13:26 UTC, Yuhu-kth commented
For the start_host_manager test, 30 containers in total, 29 passed, 1 didn't pass because its not running, don't know why it's not running yet

2024-08-13 17:35 UTC, Limmen approved these changes

2024-08-13 17:35 UTC, merged